/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manajemen_produk;

/**
 *
 * @author Administrator
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
public class login extends javax.swing.JFrame {
    
     private Connection connection;
    
  
    public login() {
        initComponents();
        this.setExtendedState(login.MAXIMIZED_BOTH);
         initializeConnection();
        
    }
    
     private void initializeConnection() {
        try {
            connection = koneksi.ConfigDB.mydatabaseconnection();
        } catch (Exception e) {
            // Log or display any exception that occurs during initialization
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed to initialize database connection: " + e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_user = new javax.swing.JTextField();
        t_pass = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_user.setFont(new java.awt.Font("Swis721 Cn BT", 1, 24)); // NOI18N
        t_user.setBorder(null);
        getContentPane().add(t_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 510, 30));

        t_pass.setFont(new java.awt.Font("Swis721 Cn BT", 1, 24)); // NOI18N
        t_pass.setBorder(null);
        getContentPane().add(t_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 462, 510, 30));

        btnLogin.setBackground(new java.awt.Color(51, 51, 51));
        btnLogin.setFont(new java.awt.Font("Swis721 Cn BT", 1, 48)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, 230, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/Manajemen-fotor-2024050875630.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
     try {
            String query = "SELECT * FROM tb_admin WHERE Username=? AND Password=?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, t_user.getText());
            statement.setString(2, t_pass.getText());
            ResultSet rs = statement.executeQuery();
            
            if(rs.next()) {
                   
                    Manajemen_produk manajemen = new  Manajemen_produk();
                    manajemen.setVisible(true);
                    dispose();
            } else {
               int option = JOptionPane.showConfirmDialog(null, "Invalid username or password. Do you want to try again?", "Invalid Login", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION) {
                // Clear text fields for re-entry
                t_user.setText("");
                t_pass.setText("");
            } else {
    
            }
            }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField t_pass;
    private javax.swing.JTextField t_user;
    // End of variables declaration//GEN-END:variables
}
