/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manajemen_produk;

/**
 *
 * @author Administrator
 */

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Manajemen_produk extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection connect=koneksi.ConfigDB.mydatabaseconnection();
    
    public Manajemen_produk() {
        initComponents();
         load_table();
        TampilData("");
        
        btnclean.setEnabled(true);
        btnedit.setEnabled(false);
        this.setExtendedState(Manajemen_produk.MAXIMIZED_BOTH);
    }
    public void load_table(){
 Object[] FieldName={
 "SKU_Product","Nama_Product","Harga_Product","Stok_product"
 };
 tabModel=new DefaultTableModel(null,FieldName);
 TB_MANAJEMEN.setModel(tabModel);
}
 
 public void TampilData(String where) {
     try{
        st=connect.createStatement();
        tabModel.getDataVector().removeAllElements();
        tabModel.fireTableDataChanged();
        rs=st.executeQuery("SELECT * FROM tb_product");
        while (rs.next()){
            Object [] data={
            rs.getString("Sku_product"),
            rs.getString("product_name"),
            rs.getString("product_price"),
            rs.getString("stock"),
            };
            
            tabModel.addRow(data);
        }
    }catch(Exception e){
    e.printStackTrace();
    }
}
  private boolean isRowSelected = false;
  
  public void reset() {
      t_sku.setText("");
      t_name.setText("");
      t_harga.setText("");
      t_stok.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_sku = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        t_harga = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        t_stok = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        btnlogout = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclean = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_MANAJEMEN = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_sku.setBorder(null);
        getContentPane().add(t_sku, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 142, 860, 40));

        t_name.setBorder(null);
        getContentPane().add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 860, 40));

        t_harga.setBorder(null);
        getContentPane().add(t_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 860, 40));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        t_stok.setBorder(null);
        getContentPane().add(t_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 870, 40));

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        btnlogout.setBackground(new java.awt.Color(255, 0, 0));
        btnlogout.setFont(new java.awt.Font("Square721 Cn BT", 1, 24)); // NOI18N
        btnlogout.setText("LogOut");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, 120, 50));

        btnsave.setBackground(new java.awt.Color(153, 255, 153));
        btnsave.setFont(new java.awt.Font("Square721 Cn BT", 1, 24)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 110, 40));

        btndelete.setBackground(new java.awt.Color(204, 0, 0));
        btndelete.setFont(new java.awt.Font("Square721 Cn BT", 1, 24)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, 110, 40));

        btnclean.setBackground(new java.awt.Color(0, 51, 255));
        btnclean.setFont(new java.awt.Font("Square721 Cn BT", 1, 24)); // NOI18N
        btnclean.setText("Clean");
        btnclean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncleanActionPerformed(evt);
            }
        });
        getContentPane().add(btnclean, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 440, 110, 40));

        btnedit.setBackground(new java.awt.Color(204, 255, 0));
        btnedit.setFont(new java.awt.Font("Swis721 Cn BT", 1, 24)); // NOI18N
        btnedit.setText("Edit");
        btnedit.setBorder(null);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 110, 40));

        TB_MANAJEMEN.setBackground(new java.awt.Color(0, 0, 0));
        TB_MANAJEMEN.setForeground(new java.awt.Color(255, 255, 255));
        TB_MANAJEMEN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TB_MANAJEMEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_MANAJEMENMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TB_MANAJEMEN);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 1180, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/SKU Produk (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
      String SKU=t_sku.getText();
      String NAMA=t_name.getText();
      String Harga=t_harga.getText();
      String Stok=t_stok.getText();
      
      try{
      st = connect.createStatement();
      String sql="select*from tb_product where Sku_product='"+SKU+"'";
      var cari=connect.prepareStatement(sql);
      rs=cari.executeQuery();
      if(rs.next()){
      JOptionPane.showMessageDialog(null,"Gagal Menyimpan Data,SKU Sudah Tersedia");
      }else{
      st.executeUpdate ("INSERT INTO tb_product (Sku_product,product_name,product_price,stock) VALUES ('"+SKU+"','"+NAMA+"','"+Harga+"','"+Stok+"')");
      TampilData("");
      JOptionPane.showMessageDialog(null,"Simpan Berhasil");
      t_sku.setText("");
      t_name.setText("");
      t_harga.setText("");
      t_stok.setText("");
      }
      }catch(Exception e){
      e.printStackTrace();
      }
    
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
      String sql="delete from tb_product where Sku_product='"+t_sku.getText()+"'";
      java.sql.Connection conn=(Connection)koneksi.ConfigDB.mydatabaseconnection();
      java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.execute();
      JOptionPane.showMessageDialog(null,"Berhasil Dihapus");
            btnsave.setEnabled(true);
            btnedit.setEnabled(false);
            btndelete.setEnabled(false);
} catch(Exception e) {
    e.printStackTrace();
}
     TampilData("");
      reset();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        try {
        st = connect.createStatement();
        String sql = "UPDATE tb_product SET " +
                     "product_name = '" + t_name.getText() + "', " +
                     "product_price = '" + t_harga.getText() + "', " +
                     "stock = '" + t_stok.getText() + "' " +
                     "WHERE Sku_product = '" + t_sku.getText() + "'";
        
        int rowsUpdated = st.executeUpdate(sql);
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            TampilData("");
            reset();
            
            // Set ulang status tombol
            btnsave.setEnabled(true);
            btnedit.setEnabled(false);
            btndelete.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mengupdate data,SKU Tidak Sesuai");
        }
    } catch(Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btneditActionPerformed

    private void TB_MANAJEMENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_MANAJEMENMouseClicked
       if (evt.getClickCount() == 1) {
        if (!isRowSelected) {
            int selectedRowIndex = TB_MANAJEMEN.getSelectedRow();
            TB_MANAJEMEN.setRowSelectionInterval(selectedRowIndex, selectedRowIndex);
            isRowSelected = true;

            t_sku.setText(TB_MANAJEMEN.getValueAt(selectedRowIndex, 0).toString());
            t_name.setText(TB_MANAJEMEN.getValueAt(selectedRowIndex, 1).toString());
            t_harga.setText(TB_MANAJEMEN.getValueAt(selectedRowIndex, 2).toString());
            t_stok.setText(TB_MANAJEMEN.getValueAt(selectedRowIndex, 3).toString());

            btnsave.setEnabled(false);
            btnedit.setEnabled(true);
            btndelete.setEnabled(true);
        } else {
            TB_MANAJEMEN.clearSelection();
            isRowSelected = false;

            t_sku.setText("");
            t_name.setText("");
            t_harga.setText("");
            t_stok.setText("");

            btnsave.setEnabled(true);
            btnedit.setEnabled(false);
            btndelete.setEnabled(false);
        }
       }
    }//GEN-LAST:event_TB_MANAJEMENMouseClicked

    private void btncleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncleanActionPerformed
        try{
            String sql="Truncate tb_product";
             java.sql.Connection conn=(Connection)koneksi.ConfigDB.mydatabaseconnection();
             java.sql.PreparedStatement pst = conn.prepareStatement(sql);
             pst.execute();
             JOptionPane.showMessageDialog(this, "Berhasil Menghapus Seluruh Database");
             btnsave.setEnabled(true);
            btnedit.setEnabled(false);
            btndelete.setEnabled(false);
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
        TampilData("");
      reset();
    }//GEN-LAST:event_btncleanActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        login loginPage = new login(); // Gantilah dengan nama kelas halaman login yang sesuai
    loginPage.setVisible(true); // Menampilkan halaman login
    dispose(); 
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manajemen_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manajemen_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manajemen_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manajemen_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manajemen_produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB_MANAJEMEN;
    private javax.swing.JButton btnclean;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_sku;
    private javax.swing.JTextField t_stok;
    // End of variables declaration//GEN-END:variables
}
